net group GG_RO_1 t /delete
net group GG_RW_1 t /delete
net group GG_RO_11 t /delete
net group GG_RW_11 t /delete
net group GG_RO_12 t /delete
net group GG_RW_12 t /delete
net group GG_RO_121 t /delete
net group GG_RW_121 t /delete
net group GG_RO_1 te /delete
net group GG_RW_1 te /delete
net group GG_RO_11 te /delete
net group GG_RW_11 te /delete
net group GG_RO_12 te /delete
net group GG_RW_12 te /delete
net group GG_RO_121 te /delete
net group GG_RW_121 te /delete
net group GG_RO_1 tes /delete
net group GG_RW_1 tes /delete
net group GG_RO_11 tes /delete
net group GG_RW_11 tes /delete
net group GG_RO_12 tes /delete
net group GG_RW_12 tes /delete
net group GG_RO_121 tes /delete
net group GG_RW_121 tes /delete
net group GG_RO_1 test /delete
net group GG_RW_1 test /delete
net group GG_RO_11 test /delete
net group GG_RW_11 test /delete
net group GG_RO_12 test /delete
net group GG_RW_12 test /delete
net group GG_RO_121 test /delete
net group GG_RW_121 test /delete
net group GG_RO_1 test2 /delete
net group GG_RW_1 test2 /delete
net group GG_RO_11 test2 /delete
net group GG_RW_11 test2 /delete
net group GG_RO_12 test2 /delete
net group GG_RW_12 test2 /delete
net group GG_RO_121 test2 /delete
net group GG_RW_121 test2 /delete
